import io
from datetime import datetime
from fpdf import FPDF
from fpdf.enums import XPos, YPos
from app.models.transaction import Transaction

class TraceabilityPDF(FPDF):
    def header(self):
        self.set_font("Helvetica", "B", 16)
        self.set_text_color(22, 101, 52)  # Dark green
        self.cell(0, 10, "KABADIWALA CONNECT", new_x=XPos.LMARGIN, new_y=YPos.NEXT, align="C")
        self.set_font("Helvetica", "B", 11)
        self.set_text_color(55, 65, 81)  # Slate gray
        self.cell(0, 6, "Platform Verified Transaction & Traceability Record", new_x=XPos.LMARGIN, new_y=YPos.NEXT, align="C")
        self.ln(4)
        self.set_draw_color(209, 213, 219)
        self.line(10, self.get_y(), 200, self.get_y())
        self.ln(6)

    def footer(self):
        self.set_y(-25)
        self.set_font("Helvetica", "I", 8)
        self.set_text_color(156, 163, 175)
        self.multi_cell(
            0, 4,
            "NOTICE: This document is a platform-side digital traceability and transaction record generated by Kabadiwala Connect.\n"
            "It must NOT be represented as an official government EPR certificate unless authorized by official integration.\n"
            f"Page {self.page_no()}",
            align="C"
        )

def generate_transaction_pdf(transaction: Transaction) -> bytes:
    pdf = TraceabilityPDF()
    pdf.add_page()
    pdf.set_auto_page_break(auto=True, margin=30)

    # Disclaimer Box
    pdf.set_fill_color(254, 243, 199)  # Warm amber background
    pdf.set_draw_color(245, 158, 11)  # Amber border
    pdf.set_text_color(146, 64, 14)  # Dark amber text
    pdf.set_font("Helvetica", "B", 9)
    pdf.rect(10, pdf.get_y(), 190, 16, style="FD")
    pdf.set_xy(12, pdf.get_y() + 2)
    pdf.multi_cell(
        186, 4,
        "PLATFORM VERIFICATION NOTICE:\n"
        "This verified transaction record certifies that scrap material was digitally recorded, pooled, physically verified, "
        "and confirmed between the verified Dealer and licensed Recycler on the Kabadiwala Connect network."
    )
    pdf.ln(8)

    # Core details
    pdf.set_font("Helvetica", "B", 12)
    pdf.set_text_color(17, 24, 39)
    pdf.cell(0, 8, "1. TRANSACTION OVERVIEW", new_x=XPos.LMARGIN, new_y=YPos.NEXT)
    pdf.ln(2)

    dealer_name = transaction.dealer.name if transaction.dealer else "Dealer"
    recycler_name = transaction.recycler.name if transaction.recycler else "Recycler"
    ts_str = transaction.timestamp.strftime("%Y-%m-%d %H:%M:%S UTC")

    details = [
        ("Transaction ID:", transaction.transaction_id),
        ("Lot ID:", transaction.lot_id),
        ("Timestamp:", ts_str),
        ("Dealer:", f"{dealer_name} (ID: {transaction.dealer_id})"),
        ("Recycler:", f"{recycler_name} (ID: {transaction.recycler_id})"),
        ("Material Category:", transaction.category),
        ("Transaction Status:", transaction.status),
    ]

    for label, val in details:
        pdf.set_font("Helvetica", "B", 10)
        pdf.set_text_color(75, 85, 99)
        pdf.cell(50, 7, label, border=0)
        pdf.set_font("Helvetica", "", 10)
        pdf.set_text_color(17, 24, 39)
        pdf.cell(0, 7, str(val), border=0, new_x=XPos.LMARGIN, new_y=YPos.NEXT)

    pdf.ln(6)

    # Audit & Weights Table
    pdf.set_font("Helvetica", "B", 12)
    pdf.set_text_color(17, 24, 39)
    pdf.cell(0, 8, "2. PHYSICAL VERIFICATION AUDIT", new_x=XPos.LMARGIN, new_y=YPos.NEXT)
    pdf.ln(2)

    # Table Header
    pdf.set_fill_color(243, 244, 246)
    pdf.set_font("Helvetica", "B", 10)
    pdf.set_text_color(31, 41, 55)
    pdf.cell(48, 8, "Declared Weight", border=1, fill=True, align="C")
    pdf.cell(48, 8, "Verified Weight", border=1, fill=True, align="C")
    pdf.cell(47, 8, "Discrepancy %", border=1, fill=True, align="C")
    pdf.cell(47, 8, "Discrepancy Flag", border=1, fill=True, align="C", new_x=XPos.LMARGIN, new_y=YPos.NEXT)

    # Table Row
    disc_flag = "WARNING (>30%)" if transaction.discrepancy_percentage > 30.0 else "NORMAL"
    pdf.set_font("Helvetica", "", 10)
    pdf.cell(48, 8, f"{transaction.declared_weight:.2f} kg", border=1, align="C")
    pdf.cell(48, 8, f"{transaction.verified_weight:.2f} kg", border=1, align="C")
    pdf.cell(47, 8, f"{transaction.discrepancy_percentage:.2f}%", border=1, align="C")
    if transaction.discrepancy_percentage > 30.0:
        pdf.set_text_color(185, 28, 28)
        pdf.set_font("Helvetica", "B", 10)
    else:
        pdf.set_text_color(31, 41, 55)
    pdf.cell(47, 8, disc_flag, border=1, align="C", new_x=XPos.LMARGIN, new_y=YPos.NEXT)

    pdf.ln(6)

    # Financial Settlement
    pdf.set_font("Helvetica", "B", 12)
    pdf.set_text_color(17, 24, 39)
    pdf.cell(0, 8, "3. SETTLEMENT DETAILS", new_x=XPos.LMARGIN, new_y=YPos.NEXT)
    pdf.ln(2)

    settlements = [
        ("Agreed Rate per kg:", f"INR {transaction.rate_per_kg:.2f} / kg", (17, 24, 39)),
        ("Verified Weight Basis:", f"{transaction.verified_weight:.2f} kg", (17, 24, 39)),
        ("Total Payout Amount:", f"INR {transaction.total_payout:.2f}", (22, 101, 52)),
    ]

    for label, val, color in settlements:
        pdf.set_font("Helvetica", "B", 10)
        pdf.set_text_color(75, 85, 99)
        pdf.cell(50, 7, label, border=0)
        pdf.set_font("Helvetica", "B" if "Total" in label else "", 10)
        pdf.set_text_color(color[0], color[1], color[2])
        pdf.cell(0, 7, str(val), border=0, new_x=XPos.LMARGIN, new_y=YPos.NEXT)

    pdf.ln(8)

    # Digital Seal Box
    pdf.set_fill_color(240, 253, 244)
    pdf.set_draw_color(34, 197, 94)
    pdf.rect(10, pdf.get_y(), 190, 20, style="FD")
    pdf.set_xy(12, pdf.get_y() + 3)
    pdf.set_font("Helvetica", "B", 9)
    pdf.set_text_color(21, 128, 61)
    pdf.cell(0, 5, "CRYPTOGRAPHIC TRACEABILITY CHAIN VERIFIED", new_x=XPos.LMARGIN, new_y=YPos.NEXT)
    pdf.set_font("Helvetica", "", 8)
    pdf.set_text_color(55, 65, 81)
    pdf.cell(0, 4, f"Status: Immutable Final Record | Platform ID: KC-TX-{transaction.transaction_id[:8].upper()}", new_x=XPos.LMARGIN, new_y=YPos.NEXT)

    buffer = io.BytesIO()
    pdf.output(buffer)
    return buffer.getvalue()
