from typing import Optional, List
from datetime import datetime
from pydantic import BaseModel, Field, ConfigDict
from app.schemas.lot import LotResponse
from app.schemas.purchase import PurchaseResponse

class HandoverVerifyRequest(BaseModel):
    verified_weight: float = Field(..., gt=0, description="Actual physical weight measured by Recycler in kg")

class HandoverVerifyResponse(BaseModel):
    lot_id: str
    category: str
    declared_weight: float
    verified_weight: float
    discrepancy_percentage: float
    discrepancy_warning: bool
    warning_message: Optional[str] = None

class ConfirmHandoverRequest(BaseModel):
    verified_weight: float = Field(..., gt=0, description="Actual physical weight measured by Recycler in kg")
    notes: Optional[str] = None

class TransactionResponse(BaseModel):
    transaction_id: str
    lot_id: str
    dealer_id: str
    dealer_name: Optional[str] = None
    recycler_id: str
    recycler_name: Optional[str] = None
    category: str
    declared_weight: float
    verified_weight: float
    discrepancy_percentage: float
    rate_per_kg: float
    total_payout: float
    status: str
    timestamp: datetime
    notes: Optional[str] = None

    model_config = ConfigDict(from_attributes=True)

class DealerLedgerSummary(BaseModel):
    dealer_id: str
    dealer_name: str
    total_spent_on_purchases: float
    total_confirmed_sales: float
    total_pending_lot_weight: float
    confirmed_transactions_count: int
    purchases_count: int
    transactions: List[TransactionResponse]
    pending_lots: List[LotResponse]

class VerifiedTransactionRecordResponse(BaseModel):
    title: str = "Platform Verified Transaction Record"
    disclaimer: str = "This document is a platform-side digital traceability and transaction record generated by Kabadiwala Connect. It is NOT an official government EPR certificate unless authorized by relevant official authorities."
    transaction_id: str
    lot_id: str
    dealer_id: str
    dealer_name: str
    recycler_id: str
    recycler_name: str
    category: str
    declared_weight_kg: float
    verified_weight_kg: float
    discrepancy_percentage: float
    rate_per_kg_inr: float
    total_payout_inr: float
    timestamp: datetime
